# LLMFS × TabPFN 3차 경량 실험 — 1×5 CV + Inner Holdout

1·2차 코드는 수정하지 않습니다. 3차는 계산량을 줄이기 위해 반복 outer CV를 `1×5`로
축소하고, 각 outer-train 내부에서 stratified holdout 한 번으로 설정을 선택합니다.

- 후보 k: `32/64/128`
- Hybrid alpha: `0.25/0.5/0.75`
- 주 비교: Adaptive Hybrid, 기존 Hybrid, Text, Data-only, MI, LASSO,
  Random 3 seeds, CatBoost-RFE, NoFS
- 공식 평가: 5개 outer-test fold를 합친 pooled OOF
- 통계: paired bootstrap 5,000회, 95% CI, Holm 보정

기본 실행 범위는 **Core TabPFN 330건**입니다. 의미 검증·모델 compatibility·embedding은
이번 경량 실행에서 제외했습니다. 모든 실행 셀은 이미 활성화되어 있습니다.

## 0. 환경과 프로젝트 불러오기

Python 3.11, CUDA PyTorch, TabPFN 8.1.0과 로컬 v2.5 checkpoint를 사용합니다.
노트북을 `3차` 폴더에서 열고 `모두 실행`을 누르세요.

In [1]:
import sys
print(sys.executable)

c:\Users\user\AppData\Local\Programs\Python\Python311\python.exe

In [2]:
from pathlib import Path
import importlib
import json
import os
import sys
import pandas as pd

candidates = [
    Path.cwd().resolve(),
    Path.home() / 'Desktop' / '2026 캡스톤_2' / '2차 실험_학회 포스터' / '3차',
]
PROJECT_ROOT = next((p for p in candidates if (p / 'EXPERIMENT_CODE').is_dir()), None)
if PROJECT_ROOT is None:
    raise FileNotFoundError('3차/EXPERIMENT_CODE 폴더를 찾지 못했습니다.')

CODE_ROOT = PROJECT_ROOT / 'EXPERIMENT_CODE'
if str(CODE_ROOT) not in sys.path:
    sys.path.insert(0, str(CODE_ROOT))

import llmfs_pipeline as exp
exp = importlib.reload(exp)
CFG = exp.load_config(CODE_ROOT / 'experiment_config.json')
PATHS = exp.init_result_dirs(CFG)
exp.seed_everything(int(CFG['seeds']['global_seed']))

print('Pipeline:', exp.PIPELINE_VERSION)
print('Project:', PROJECT_ROOT)
print('Data:', CFG['data_root'])
print('Results:', CFG['results_root'])

Pipeline: 4.1.1
Project: C:\Users\user\Desktop\2026 캡스톤_2차\2차 실험_KDMS\3차
Data: C:\Users\user\Desktop\2026 캡스톤_2차\2차 실험_KDMS\DATA
Results: C:\Users\user\Desktop\2026 캡스톤_2차\2차 실험_KDMS\3차\RESULTS_LIGHT_1X5_HOLDOUT

In [3]:
env = exp.environment_report(CFG, require_cuda=True)
display(env)
assert env['cuda_available'] is True
assert env['tabpfn_checkpoint']['is_file'] is True
print('CUDA / local TabPFN checkpoint: PASS')

{'created_at': '2026-08-14T05:40:46.790554+00:00',
 'pipeline_version': '4.1.1',
 'python': '3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]',
 'executable': 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\python.exe',
 'platform': 'Windows-10-10.0.19045-SP0',
 'cuda_available': True,
 'cuda_device': 'NVIDIA GeForce RTX 4060 Ti',
 'torch_cuda_runtime': '13.0',
 'torch_error': None,
 'tabpfn_checkpoint': {'path': 'C:\\Users\\user\\Desktop\\2026 캡스톤_2차\\tabpfn-v2.5-classifier-v2.5_default.ckpt\\tabpfn-v2.5-classifier-v2.5_default.ckpt',
  'exists': True,
  'is_file': True,
  'size_bytes': 42935499},
 'packages': {'numpy': '1.26.4',
  'pandas': '3.0.2',
  'scipy': '1.16.3',
  'scikit-learn': '1.8.0',
  'catboost': '1.2.10',
  'tabpfn': '8.1.0',
  'tabpfn-extensions': '0.5.0',
  'google-genai': '2.17.0',
  'torch': '2.11.0+cu130',
  'umap-learn': '0.5.12'},
 'config_hash': '677e7d670a961887fcab4c15c24492cd9451188f3007495506edca593c4ddf6e'}

CUDA / local TabPFN checkpoint: PASS

## 1. 데이터·1×5 outer CV·내부 holdout 검사

소표본화는 outer-train에만 적용합니다. Inner holdout은 outer-train의 약 75%로 특징을
선택·학습하고 나머지 약 25%로 k·alpha를 고릅니다. Outer-test는 설정 선택에 사용하지 않습니다.

In [4]:
data_summary = exp.validate_all_data(CFG)
mapping_report = exp.semantic_mapping_report(CFG, raise_on_failure=True)
display(data_summary)
display(mapping_report)

assert set(data_summary['dataset']) == {'colon', 'golub', 'metabric'}
assert (data_summary['outer_repeats'] == 1).all()
assert (data_summary['outer_folds'] == 5).all()
assert mapping_report['passed'].all()
assert CFG['nested_tuning']['strategy'] == 'stratified_holdout'
assert int(CFG['nested_tuning']['inner_folds']) == 1
assert CFG['nested_tuning']['k_grid'] == [32, 64, 128]
assert CFG['nested_tuning']['alpha_grid'] == [0.25, 0.5, 0.75]
assert CFG['execution']['enabled_stages'] == ['core']
print('Data / 1×5 outer CV / one inner holdout: PASS')

,dataset,n,p,p_over_n,class_0,class_1,source_outer_repeats,source_outer_folds,outer_repeats,outer_folds,split_strategy,smallest_test_fold
0,golub,72,3051,42.375000,47,25,10,5,1,5,generated_stratified,14
1,colon,62,1991,32.112903,22,40,10,5,1,5,generated_stratified,12
2,metabric,1904,684,0.359244,801,1103,10,5,1,5,generated_stratified,380

,dataset,n_features,real_name_column,n_nonempty_real_names,n_gene_symbols,gene_symbol_coverage,required_minimum,mapping_required,passed
0,golub,3051,semantic_name,3051,1607,0.526713,0.5,True,True
1,colon,1991,semantic_name,1991,517,0.259669,0.2,True,True
2,metabric,684,semantic_name,684,662,0.967836,0.0,False,True

Data / 1×5 outer CV / one inner holdout: PASS

In [5]:
execution_plan = exp.experiment_execution_plan(CFG)
display(execution_plan)

core_grid = exp.build_experiment_grid(CFG, 'core')
assert len(core_grid) == 330
assert int(execution_plan.loc[execution_plan['stage'] == 'TOTAL', 'model_runs'].iloc[0]) == 330
print('Core outer runs:', len(core_grid))
print('Expected inner Logistic fits: 1,260')
print('Paired fold-seed base:', CFG['seeds']['model_seed'])

   stage   model  model_runs
0   core  tabpfn         330
1  TOTAL     all         330

Core outer runs: 330
Expected inner Logistic fits: 1,260
Paired fold-seed base: 20260818

## 2. Gemini score 준비

특징 이름과 task가 같은 2차 LLM 점수를 feature ID와 설정 기준으로 검증해 재사용합니다.
검증 실패 시에만 API key를 입력하고 기존 Gemini Batch를 실행합니다.

In [6]:
RUN_LLM_PREPARE = True
if RUN_LLM_PREPARE:
    llm_cache = exp.reuse_llm_score_cache(CFG)
    display(llm_cache)
    if not llm_cache['ready']:
        display(exp.llm_execution_plan(CFG))
        _gemini_key = exp.ensure_gemini_api_key()
        display(exp.submit_all_llm_jobs(CFG, confirm='SUBMIT_GEMINI_BATCH_JOBS'))
        for condition, runs in [('real', int(CFG['llm']['real_runs'])), ('anonymous', int(CFG['llm']['anonymous_runs']))]:
            for run_index in range(1, runs + 1):
                status = exp.get_llm_job_status(CFG, condition, run_index)
                if status['state'] != 'JOB_STATE_SUCCEEDED':
                    status = exp.wait_for_llm_job(CFG, condition, run_index, timeout_hours=24.0)
                if status['state'] != 'JOB_STATE_SUCCEEDED':
                    raise RuntimeError(f'Gemini Batch failed: {condition}/run{run_index}: {status}')
        display(exp.retrieve_and_prepare_all_llm_scores(CFG))

llm_status = exp.llm_score_cache_status(CFG)
display(llm_status)
assert llm_status['valid'].all()
print('All LLM scores: READY')

{'source': 'current_results', 'copied_files': 0, 'ready': True}

,dataset,condition,exists,valid,n_features,path
0,golub,real,True,True,3051,C:\Users\user\Desktop\2026 캡스톤_2차\2차 실험_KDMS\3...
1,golub,anonymous,True,True,3051,C:\Users\user\Desktop\2026 캡스톤_2차\2차 실험_KDMS\3...
2,golub,permuted_seed_0007,True,True,3051,C:\Users\user\Desktop\2026 캡스톤_2차\2차 실험_KDMS\3...
3,golub,permuted_seed_0019,True,True,3051,C:\Users\user\Desktop\2026 캡스톤_2차\2차 실험_KDMS\3...
4,golub,permuted_seed_0031,True,True,3051,C:\Users\user\Desktop\2026 캡스톤_2차\2차 실험_KDMS\3...
5,colon,real,True,True,1991,C:\Users\user\Desktop\2026 캡스톤_2차\2차 실험_KDMS\3...
6,colon,anonymous,True,True,1991,C:\Users\user\Desktop\2026 캡스톤_2차\2차 실험_KDMS\3...
7,colon,permuted_seed_0007,True,True,1991,C:\Users\user\Desktop\2026 캡스톤_2차\2차 실험_KDMS\3...
8,colon,permuted_seed_0019,True,True,1991,C:\Users\user\Desktop\2026 캡스톤_2차\2차 실험_KDMS\3...
9,colon,permuted_seed_0031,True,True,1991,C:\Users\user\Desktop\2026 캡스톤_2차\2차 실험_KDMS\3...
10,metabric,real,True,True,684,C:\Users\user\Desktop\2026 캡스톤_2차\2차 실험_KDMS\3...
11,metabric,anonymous,True,True,684,C:\Users\user\Desktop\2026 캡스톤_2차\2차 실험_KDMS\3...
12,metabric,permuted_seed_0007,True,True,684,C:\Users\user\Desktop\2026 캡스톤_2차\2차 실험_KDMS\3...
13,metabric,permuted_seed_0019,True,True,684,C:\Users\user\Desktop\2026 캡스톤_2차\2차 실험_KDMS\3...
14,metabric,permuted_seed_0031,True,True,684,C:\Users\user\Desktop\2026 캡스톤_2차\2차 실험_KDMS\3...

All LLM scores: READY

## 3. 실행 전 smoke test

In [7]:
RUN_SMOKE = True
if RUN_SMOKE:
    smoke_status = exp.run_grid(CFG, exp.build_experiment_grid(CFG, 'smoke'))
    display(smoke_status)
    assert (smoke_status['status'] == 'completed').all()

[1/2] colon mi logistic r1f1 [saved fold reused]
[2/2] colon random logistic r1f1 [saved fold reused]

,stage,dataset,sample_regime,repeat,fold,method,condition,k,alpha,selector_seed,model,status,prediction_path,resume_hit,wall_seconds,error
0,smoke,colon,full,1,1,mi,name_invariant,8,0.5,7,logistic,completed,C:\Users\user\Desktop\2026 캡스톤_2차\2차 실험_KDMS\3...,True,0.000003,None
1,smoke,colon,full,1,1,random,name_invariant,8,0.5,7,logistic,completed,C:\Users\user\Desktop\2026 캡스톤_2차\2차 실험_KDMS\3...,True,0.000003,None

## 4. 주 분석 — Core TabPFN 330건

모든 방법은 동일한 inner holdout과 k 후보를 사용합니다. Hybrid 두 방식만 alpha 후보를
추가합니다. Inner holdout으로 선택된 설정을 outer-train 전체에 다시 적용하고 outer-test를
TabPFN으로 예측합니다.

In [8]:
RUN_CORE = True
if RUN_CORE:
    # This cell can be rerun directly after an interruption. Reload the patched
    # pipeline and reuse every exact fold prediction already saved on disk.
    exp = importlib.reload(exp)
    CFG = exp.load_config(CODE_ROOT / 'experiment_config.json')
    core_grid = exp.build_experiment_grid(CFG, 'core')
    saved_before = sum(
        exp.prediction_path(CFG, row.where(pd.notna(row), None).to_dict()).is_file()
        for _, row in core_grid.iterrows()
    )
    print(f'Resume mode: {saved_before}/{len(core_grid)} saved folds will not be retrained.')
    core_status = exp.run_grid(CFG, core_grid)
    display(core_status[['status', 'resume_hit']].value_counts(dropna=False))
    assert (core_status['status'] == 'completed').all()

Resume mode: 262/330 saved folds will not be retrained.
[1/330] golub text tabpfn r1f1 [saved fold reused]
[2/330] golub hybrid tabpfn r1f1 [saved fold reused]
[3/330] golub adaptive_hybrid tabpfn r1f1 [saved fold reused]
[4/330] golub data_only tabpfn r1f1 [saved fold reused]
[5/330] golub mi tabpfn r1f1 [saved fold reused]
[6/330] golub lasso tabpfn r1f1 [saved fold reused]
[7/330] golub random tabpfn r1f1 [saved fold reused]
[8/330] golub random tabpfn r1f1 [saved fold reused]
[9/330] golub random tabpfn r1f1 [saved fold reused]
[10/330] golub catboost_rfe tabpfn r1f1 [saved fold reused]
[11/330] golub no_fs tabpfn r1f1 [saved fold reused]
[12/330] golub text tabpfn r1f2 [saved fold reused]
[13/330] golub hybrid tabpfn r1f2 [saved fold reused]
[14/330] golub adaptive_hybrid tabpfn r1f2 [saved fold reused]
[15/330] golub data_only tabpfn r1f2 [saved fold reused]
[16/330] golub mi tabpfn r1f2 [saved fold reused]
[17/330] golub lasso tabpfn r1f2 [saved fold reused]
[18/330] golub random tabpfn r1f2 [saved fold reused]
[19/330] golub random tabpfn r1f2 [saved fold reused]
[20/330] golub random tabpfn r1f2 [saved fold reused]
[21/330] golub catboost_rfe tabpfn r1f2 [saved fold reused]
[22/330] golub no_fs tabpfn r1f2 [saved fold reused]
[23/330] golub text tabpfn r1f3 [saved fold reused]
[24/330] golub hybrid tabpfn r1f3 [saved fold reused]
[25/330] golub adaptive_hybrid tabpfn r1f3 [saved fold reused]
[26/330] golub data_only tabpfn r1f3 [saved fold reused]
[27/330] golub mi tabpfn r1f3 [saved fold reused]
[28/330] golub lasso tabpfn r1f3 [saved fold reused]
[29/330] golub random tabpfn r1f3 [saved fold reused]
[30/330] golub random tabpfn r1f3 [saved fold reused]
[31/330] golub random tabpfn r1f3 [saved fold reused]
[32/330] golub catboost_rfe tabpfn r1f3 [saved fold reused]
[33/330] golub no_fs tabpfn r1f3 [saved fold reused]
[34/330] golub text tabpfn r1f4 [saved fold reused]
[35/330] golub hybrid tabpfn r1f4 [saved fold reused]
[36/330] golub adaptive_hybrid tabpfn r1f4 [saved fold reused]
[37/330] golub data_only tabpfn r1f4 [saved fold reused]
[38/330] golub mi tabpfn r1f4 [saved fold reused]
[39/330] golub lasso tabpfn r1f4 [saved fold reused]
[40/330] golub random tabpfn r1f4 [saved fold reused]
[41/330] golub random tabpfn r1f4 [saved fold reused]
[42/330] golub random tabpfn r1f4 [saved fold reused]
[43/330] golub catboost_rfe tabpfn r1f4 [saved fold reused]
[44/330] golub no_fs tabpfn r1f4 [saved fold reused]
[45/330] golub text tabpfn r1f5 [saved fold reused]
[46/330] golub hybrid tabpfn r1f5 [saved fold reused]
[47/330] golub adaptive_hybrid tabpfn r1f5 [saved fold reused]
[48/330] golub data_only tabpfn r1f5 [saved fold reused]
[49/330] golub mi tabpfn r1f5 [saved fold reused]
[50/330] golub lasso tabpfn r1f5 [saved fold reused]
[51/330] golub random tabpfn r1f5 [saved fold reused]
[52/330] golub random tabpfn r1f5 [saved fold reused]
[53/330] golub random tabpfn r1f5 [saved fold reused]
[54/330] golub catboost_rfe tabpfn r1f5 [saved fold reused]
[55/330] golub no_fs tabpfn r1f5 [saved fold reused]
[56/330] golub text tabpfn r1f1 [saved fold reused]
[57/330] golub hybrid tabpfn r1f1 [saved fold reused]
[58/330] golub adaptive_hybrid tabpfn r1f1 [saved fold reused]
[59/330] golub data_only tabpfn r1f1 [saved fold reused]
[60/330] golub mi tabpfn r1f1 [saved fold reused]
[61/330] golub lasso tabpfn r1f1 [saved fold reused]
[62/330] golub random tabpfn r1f1 [saved fold reused]
[63/330] golub random tabpfn r1f1 [saved fold reused]
[64/330] golub random tabpfn r1f1 [saved fold reused]
[65/330] golub catboost_rfe tabpfn r1f1 [saved fold reused]
[66/330] golub no_fs tabpfn r1f1 [saved fold reused]
[67/330] golub text tabpfn r1f2 [saved fold reused]
[68/330] golub hybrid tabpfn r1f2 [saved fold reused]
[69/330] golub adaptive_hybrid tabpfn r1f2 [saved fold reused]
[70/330] golub data_only tabpfn r1f2 [saved fold reused]
[71/330] golub mi tabpfn r1f2 [saved fold reused]
[72/330] golub lasso tabpfn r1f2 [saved fold reused]
[73/330] golub random tabpfn r1f2 [saved fold reused]
[74/330] golub random tabpfn r1f2 [saved fold reused]
[75/330] golub random tabpfn r1f2 [saved fold reused]
[76/330] golub catboost_rfe tabpfn r1f2 [saved fold reused]
[77/330] golub no_fs tabpfn r1f2 [saved fold reused]
[78/330] golub text tabpfn r1f3 [saved fold reused]
[79/330] golub hybrid tabpfn r1f3 [saved fold reused]
[80/330] golub adaptive_hybrid tabpfn r1f3 [saved fold reused]
[81/330] golub data_only tabpfn r1f3 [saved fold reused]
[82/330] golub mi tabpfn r1f3 [saved fold reused]
[83/330] golub lasso tabpfn r1f3 [saved fold reused]
[84/330] golub random tabpfn r1f3 [saved fold reused]
[85/330] golub random tabpfn r1f3 [saved fold reused]
[86/330] golub random tabpfn r1f3 [saved fold reused]
[87/330] golub catboost_rfe tabpfn r1f3 [saved fold reused]
[88/330] golub no_fs tabpfn r1f3 [saved fold reused]
[89/330] golub text tabpfn r1f4 [saved fold reused]
[90/330] golub hybrid tabpfn r1f4 [saved fold reused]
[91/330] golub adaptive_hybrid tabpfn r1f4 [saved fold reused]
[92/330] golub data_only tabpfn r1f4 [saved fold reused]
[93/330] golub mi tabpfn r1f4 [saved fold reused]
[94/330] golub lasso tabpfn r1f4 [saved fold reused]
[95/330] golub random tabpfn r1f4 [saved fold reused]
[96/330] golub random tabpfn r1f4 [saved fold reused]
[97/330] golub random tabpfn r1f4 [saved fold reused]
[98/330] golub catboost_rfe tabpfn r1f4 [saved fold reused]
[99/330] golub no_fs tabpfn r1f4 [saved fold reused]
[100/330] golub text tabpfn r1f5 [saved fold reused]
[101/330] golub hybrid tabpfn r1f5 [saved fold reused]
[102/330] golub adaptive_hybrid tabpfn r1f5 [saved fold reused]
[103/330] golub data_only tabpfn r1f5 [saved fold reused]
[104/330] golub mi tabpfn r1f5 [saved fold reused]
[105/330] golub lasso tabpfn r1f5 [saved fold reused]
[106/330] golub random tabpfn r1f5 [saved fold reused]
[107/330] golub random tabpfn r1f5 [saved fold reused]
[108/330] golub random tabpfn r1f5 [saved fold reused]
[109/330] golub catboost_rfe tabpfn r1f5 [saved fold reused]
[110/330] golub no_fs tabpfn r1f5 [saved fold reused]
[111/330] colon text tabpfn r1f1 [saved fold reused]
[112/330] colon hybrid tabpfn r1f1 [saved fold reused]
[113/330] colon adaptive_hybrid tabpfn r1f1 [saved fold reused]
[114/330] colon data_only tabpfn r1f1 [saved fold reused]
[115/330] colon mi tabpfn r1f1 [saved fold reused]
[116/330] colon lasso tabpfn r1f1 [saved fold reused]
[117/330] colon random tabpfn r1f1 [saved fold reused]
[118/330] colon random tabpfn r1f1 [saved fold reused]
[119/330] colon random tabpfn r1f1 [saved fold reused]
[120/330] colon catboost_rfe tabpfn r1f1 [saved fold reused]
[121/330] colon no_fs tabpfn r1f1 [saved fold reused]
[122/330] colon text tabpfn r1f2 [saved fold reused]
[123/330] colon hybrid tabpfn r1f2 [saved fold reused]
[124/330] colon adaptive_hybrid tabpfn r1f2 [saved fold reused]
[125/330] colon data_only tabpfn r1f2 [saved fold reused]
[126/330] colon mi tabpfn r1f2 [saved fold reused]
[127/330] colon lasso tabpfn r1f2 [saved fold reused]
[128/330] colon random tabpfn r1f2 [saved fold reused]
[129/330] colon random tabpfn r1f2 [saved fold reused]
[130/330] colon random tabpfn r1f2 [saved fold reused]
[131/330] colon catboost_rfe tabpfn r1f2 [saved fold reused]
[132/330] colon no_fs tabpfn r1f2 [saved fold reused]
[133/330] colon text tabpfn r1f3 [saved fold reused]
[134/330] colon hybrid tabpfn r1f3 [saved fold reused]
[135/330] colon adaptive_hybrid tabpfn r1f3 [saved fold reused]
[136/330] colon data_only tabpfn r1f3 [saved fold reused]
[137/330] colon mi tabpfn r1f3 [saved fold reused]
[138/330] colon lasso tabpfn r1f3 [saved fold reused]
[139/330] colon random tabpfn r1f3 [saved fold reused]
[140/330] colon random tabpfn r1f3 [saved fold reused]
[141/330] colon random tabpfn r1f3 [saved fold reused]
[142/330] colon catboost_rfe tabpfn r1f3 [saved fold reused]
[143/330] colon no_fs tabpfn r1f3 [saved fold reused]
[144/330] colon text tabpfn r1f4 [saved fold reused]
[145/330] colon hybrid tabpfn r1f4 [saved fold reused]
[146/330] colon adaptive_hybrid tabpfn r1f4 [saved fold reused]
[147/330] colon data_only tabpfn r1f4 [saved fold reused]
[148/330] colon mi tabpfn r1f4 [saved fold reused]
[149/330] colon lasso tabpfn r1f4 [saved fold reused]
[150/330] colon random tabpfn r1f4 [saved fold reused]
[151/330] colon random tabpfn r1f4 [saved fold reused]
[152/330] colon random tabpfn r1f4 [saved fold reused]
[153/330] colon catboost_rfe tabpfn r1f4 [saved fold reused]
[154/330] colon no_fs tabpfn r1f4 [saved fold reused]
[155/330] colon text tabpfn r1f5 [saved fold reused]
[156/330] colon hybrid tabpfn r1f5 [saved fold reused]
[157/330] colon adaptive_hybrid tabpfn r1f5 [saved fold reused]
[158/330] colon data_only tabpfn r1f5 [saved fold reused]
[159/330] colon mi tabpfn r1f5 [saved fold reused]
[160/330] colon lasso tabpfn r1f5 [saved fold reused]
[161/330] colon random tabpfn r1f5 [saved fold reused]
[162/330] colon random tabpfn r1f5 [saved fold reused]
[163/330] colon random tabpfn r1f5 [saved fold reused]
[164/330] colon catboost_rfe tabpfn r1f5 [saved fold reused]
[165/330] colon no_fs tabpfn r1f5 [saved fold reused]
[166/330] colon text tabpfn r1f1 [saved fold reused]
[167/330] colon hybrid tabpfn r1f1 [saved fold reused]
[168/330] colon adaptive_hybrid tabpfn r1f1 [saved fold reused]
[169/330] colon data_only tabpfn r1f1 [saved fold reused]
[170/330] colon mi tabpfn r1f1 [saved fold reused]
[171/330] colon lasso tabpfn r1f1 [saved fold reused]
[172/330] colon random tabpfn r1f1 [saved fold reused]
[173/330] colon random tabpfn r1f1 [saved fold reused]
[174/330] colon random tabpfn r1f1 [saved fold reused]
[175/330] colon catboost_rfe tabpfn r1f1 [saved fold reused]
[176/330] colon no_fs tabpfn r1f1 [saved fold reused]
[177/330] colon text tabpfn r1f2 [saved fold reused]
[178/330] colon hybrid tabpfn r1f2 [saved fold reused]
[179/330] colon adaptive_hybrid tabpfn r1f2 [saved fold reused]
[180/330] colon data_only tabpfn r1f2 [saved fold reused]
[181/330] colon mi tabpfn r1f2 [saved fold reused]
[182/330] colon lasso tabpfn r1f2 [saved fold reused]
[183/330] colon random tabpfn r1f2 [saved fold reused]
[184/330] colon random tabpfn r1f2 [saved fold reused]
[185/330] colon random tabpfn r1f2 [saved fold reused]
[186/330] colon catboost_rfe tabpfn r1f2 [saved fold reused]
[187/330] colon no_fs tabpfn r1f2 [saved fold reused]
[188/330] colon text tabpfn r1f3 [saved fold reused]
[189/330] colon hybrid tabpfn r1f3 [saved fold reused]
[190/330] colon adaptive_hybrid tabpfn r1f3 [saved fold reused]
[191/330] colon data_only tabpfn r1f3 [saved fold reused]
[192/330] colon mi tabpfn r1f3 [saved fold reused]
[193/330] colon lasso tabpfn r1f3 [saved fold reused]
[194/330] colon random tabpfn r1f3 [saved fold reused]
[195/330] colon random tabpfn r1f3 [saved fold reused]
[196/330] colon random tabpfn r1f3 [saved fold reused]
[197/330] colon catboost_rfe tabpfn r1f3 [saved fold reused]
[198/330] colon no_fs tabpfn r1f3 [saved fold reused]
[199/330] colon text tabpfn r1f4 [saved fold reused]
[200/330] colon hybrid tabpfn r1f4 [saved fold reused]
[201/330] colon adaptive_hybrid tabpfn r1f4 [saved fold reused]
[202/330] colon data_only tabpfn r1f4 [saved fold reused]
[203/330] colon mi tabpfn r1f4 [saved fold reused]
[204/330] colon lasso tabpfn r1f4 [saved fold reused]
[205/330] colon random tabpfn r1f4 [saved fold reused]
[206/330] colon random tabpfn r1f4 [saved fold reused]
[207/330] colon random tabpfn r1f4 [saved fold reused]
[208/330] colon catboost_rfe tabpfn r1f4 [saved fold reused]
[209/330] colon no_fs tabpfn r1f4 [saved fold reused]
[210/330] colon text tabpfn r1f5 [saved fold reused]
[211/330] colon hybrid tabpfn r1f5 [saved fold reused]
[212/330] colon adaptive_hybrid tabpfn r1f5 [saved fold reused]
[213/330] colon data_only tabpfn r1f5 [saved fold reused]
[214/330] colon mi tabpfn r1f5 [saved fold reused]
[215/330] colon lasso tabpfn r1f5 [saved fold reused]
[216/330] colon random tabpfn r1f5 [saved fold reused]
[217/330] colon random tabpfn r1f5 [saved fold reused]
[218/330] colon random tabpfn r1f5 [saved fold reused]
[219/330] colon catboost_rfe tabpfn r1f5 [saved fold reused]
[220/330] colon no_fs tabpfn r1f5 [saved fold reused]
[221/330] metabric text tabpfn r1f1

c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

[222/330] metabric hybrid tabpfn r1f1
[223/330] metabric adaptive_hybrid tabpfn r1f1
[224/330] metabric data_only tabpfn r1f1 [saved fold reused]
[225/330] metabric mi tabpfn r1f1 [saved fold reused]
[226/330] metabric lasso tabpfn r1f1
[227/330] metabric random tabpfn r1f1
[228/330] metabric random tabpfn r1f1
[229/330] metabric random tabpfn r1f1
[230/330] metabric catboost_rfe tabpfn r1f1 [saved fold reused]
[231/330] metabric no_fs tabpfn r1f1 [saved fold reused]
[232/330] metabric text tabpfn r1f2
[233/330] metabric hybrid tabpfn r1f2
[234/330] metabric adaptive_hybrid tabpfn r1f2
[235/330] metabric data_only tabpfn r1f2
[236/330] metabric mi tabpfn r1f2 [saved fold reused]
[237/330] metabric lasso tabpfn r1f2 [saved fold reused]
[238/330] metabric random tabpfn r1f2
[239/330] metabric random tabpfn r1f2
[240/330] metabric random tabpfn r1f2
[241/330] metabric catboost_rfe tabpfn r1f2 [saved fold reused]
[242/330] metabric no_fs tabpfn r1f2 [saved fold reused]
[243/330] metabric text tabpfn r1f3
[244/330] metabric hybrid tabpfn r1f3
[245/330] metabric adaptive_hybrid tabpfn r1f3
[246/330] metabric data_only tabpfn r1f3
[247/330] metabric mi tabpfn r1f3 [saved fold reused]
[248/330] metabric lasso tabpfn r1f3 [saved fold reused]
[249/330] metabric random tabpfn r1f3
[250/330] metabric random tabpfn r1f3
[251/330] metabric random tabpfn r1f3
[252/330] metabric catboost_rfe tabpfn r1f3 [saved fold reused]
[253/330] metabric no_fs tabpfn r1f3 [saved fold reused]
[254/330] metabric text tabpfn r1f4
[255/330] metabric hybrid tabpfn r1f4
[256/330] metabric adaptive_hybrid tabpfn r1f4
[257/330] metabric data_only tabpfn r1f4
[258/330] metabric mi tabpfn r1f4 [saved fold reused]
[259/330] metabric lasso tabpfn r1f4 [saved fold reused]
[260/330] metabric random tabpfn r1f4
[261/330] metabric random tabpfn r1f4
[262/330] metabric random tabpfn r1f4
[263/330] metabric catboost_rfe tabpfn r1f4 [saved fold reused]
[264/330] metabric no_fs tabpfn r1f4 [saved fold reused]
[265/330] metabric text tabpfn r1f5
[266/330] metabric hybrid tabpfn r1f5
[267/330] metabric adaptive_hybrid tabpfn r1f5
[268/330] metabric data_only tabpfn r1f5
[269/330] metabric mi tabpfn r1f5 [saved fold reused]
[270/330] metabric lasso tabpfn r1f5
[271/330] metabric random tabpfn r1f5
[272/330] metabric random tabpfn r1f5
[273/330] metabric random tabpfn r1f5
[274/330] metabric catboost_rfe tabpfn r1f5 [saved fold reused]
[275/330] metabric no_fs tabpfn r1f5 [saved fold reused]
[276/330] metabric text tabpfn r1f1
[277/330] metabric hybrid tabpfn r1f1
[278/330] metabric adaptive_hybrid tabpfn r1f1
[279/330] metabric data_only tabpfn r1f1 [saved fold reused]
[280/330] metabric mi tabpfn r1f1
[281/330] metabric lasso tabpfn r1f1 [saved fold reused]
[282/330] metabric random tabpfn r1f1
[283/330] metabric random tabpfn r1f1
[284/330] metabric random tabpfn r1f1
[285/330] metabric catboost_rfe tabpfn r1f1 [saved fold reused]
[286/330] metabric no_fs tabpfn r1f1 [saved fold reused]
[287/330] metabric text tabpfn r1f2
[288/330] metabric hybrid tabpfn r1f2
[289/330] metabric adaptive_hybrid tabpfn r1f2
[290/330] metabric data_only tabpfn r1f2
[291/330] metabric mi tabpfn r1f2
[292/330] metabric lasso tabpfn r1f2 [saved fold reused]
[293/330] metabric random tabpfn r1f2
[294/330] metabric random tabpfn r1f2
[295/330] metabric random tabpfn r1f2
[296/330] metabric catboost_rfe tabpfn r1f2 [saved fold reused]
[297/330] metabric no_fs tabpfn r1f2 [saved fold reused]
[298/330] metabric text tabpfn r1f3
[299/330] metabric hybrid tabpfn r1f3
[300/330] metabric adaptive_hybrid tabpfn r1f3
[301/330] metabric data_only tabpfn r1f3
[302/330] metabric mi tabpfn r1f3
[303/330] metabric lasso tabpfn r1f3 [saved fold reused]
[304/330] metabric random tabpfn r1f3 [saved fold reused]
[305/330] metabric random tabpfn r1f3
[306/330] metabric random tabpfn r1f3
[307/330] metabric catboost_rfe tabpfn r1f3 [saved fold reused]
[308/330] metabric no_fs tabpfn r1f3 [saved fold reused]
[309/330] metabric text tabpfn r1f4
[310/330] metabric hybrid tabpfn r1f4
[311/330] metabric adaptive_hybrid tabpfn r1f4
[312/330] metabric data_only tabpfn r1f4 [saved fold reused]
[313/330] metabric mi tabpfn r1f4
[314/330] metabric lasso tabpfn r1f4 [saved fold reused]
[315/330] metabric random tabpfn r1f4 [saved fold reused]
[316/330] metabric random tabpfn r1f4 [saved fold reused]
[317/330] metabric random tabpfn r1f4
[318/330] metabric catboost_rfe tabpfn r1f4 [saved fold reused]
[319/330] metabric no_fs tabpfn r1f4 [saved fold reused]
[320/330] metabric text tabpfn r1f5
[321/330] metabric hybrid tabpfn r1f5
[322/330] metabric adaptive_hybrid tabpfn r1f5
[323/330] metabric data_only tabpfn r1f5 [saved fold reused]
[324/330] metabric mi tabpfn r1f5 [saved fold reused]
[325/330] metabric lasso tabpfn r1f5 [saved fold reused]
[326/330] metabric random tabpfn r1f5 [saved fold reused]
[327/330] metabric random tabpfn r1f5
[328/330] metabric random tabpfn r1f5
[329/330] metabric catboost_rfe tabpfn r1f5 [saved fold reused]
[330/330] metabric no_fs tabpfn r1f5 [saved fold reused]

status     resume_hit
completed  True          262
           False          68
Name: count, dtype: int64

## 5. OOF 성능·설정 선택·안정성·통계

Random은 세 selector seed의 확률을 표본별 평균합니다. Adaptive Hybrid를 기준으로 모든
비교 방법과 paired bootstrap을 수행합니다.

In [9]:
RUN_METRICS = True
if RUN_METRICS:
    predictions = exp.consolidate_predictions(CFG)
    repeat_metrics = exp.aggregate_repeat_metrics(CFG, predictions)
    fold_metrics = exp.aggregate_fold_metrics(CFG, predictions)
    fold_variability = exp.summarize_fold_variability(CFG, fold_metrics)
    metric_summary = exp.summarize_metrics(CFG, repeat_metrics)
    primary_oof = exp.primary_core_oof_metrics(CFG, predictions)
    tuning_decisions = exp.consolidate_tuning_decisions(CFG)
    stability = exp.compute_selection_stability(CFG)
    selection_frequency = exp.compute_selection_frequency(CFG)
    bootstrap = exp.paired_bootstrap_auroc(CFG, predictions, reference_method='adaptive_hybrid')

    display(primary_oof.sort_values(['dataset', 'sample_regime', 'auroc'], ascending=[True, True, False]))
    display(tuning_decisions.loc[tuning_decisions['stage'] == 'core'].head(30))
    display(bootstrap.sort_values(['dataset', 'sample_regime', 'delta_auroc'], ascending=[True, True, False]))
    assert len(primary_oof) == 54
    assert len(bootstrap) == 48
    complete = stability.loc[(stability['stage'] == 'core') & stability['complete_outer_cv']]
    assert (complete['n_pairs'] == 10).all()

C:\Users\user\Desktop\2026 캡스톤_2차\2차 실험_KDMS\3차\EXPERIMENT_CODE\llmfs_pipeline.py:2507: RuntimeWarning: Mean of empty slice
  "mean_kuncheva": float(np.nanmean(kuncheva)) if kuncheva else float("nan"),
C:\Users\user\Desktop\2026 캡스톤_2차\2차 실험_KDMS\3차\EXPERIMENT_CODE\llmfs_pipeline.py:2507: RuntimeWarning: Mean of empty slice
  "mean_kuncheva": float(np.nanmean(kuncheva)) if kuncheva else float("nan"),

,dataset,sample_regime,method,auroc,average_precision,ap_lift,log_loss,brier,mcc,balanced_accuracy,sensitivity,specificity,ece,prevalence,n_oof,n_outer_repeats,n_selector_seeds
0,colon,24,adaptive_hybrid,0.852273,0.900071,1.395110,0.490048,0.150743,0.547014,0.776136,0.825000,0.727273,0.091282,0.645161,62,1,1
1,colon,24,catboost_rfe,0.837500,0.909851,1.410269,0.513711,0.163352,0.587147,0.798864,0.825000,0.772727,0.135759,0.645161,62,1,1
6,colon,24,no_fs,0.829545,0.889652,1.378960,0.500370,0.159486,0.608882,0.801136,0.875000,0.727273,0.133719,0.645161,62,1,1
7,colon,24,random,0.829545,0.858154,1.330139,0.490409,0.157210,0.466426,0.730682,0.825000,0.636364,0.111277,0.645161,62,1,3
8,colon,24,text,0.813636,0.890042,1.379565,0.513750,0.168426,0.506818,0.753409,0.825000,0.681818,0.142553,0.645161,62,1,1
3,colon,24,hybrid,0.794318,0.878593,1.361820,0.567498,0.176159,0.517940,0.763636,0.800000,0.727273,0.159015,0.645161,62,1,1
2,colon,24,data_only,0.793182,0.848703,1.315490,0.560020,0.174453,0.506818,0.753409,0.825000,0.681818,0.115255,0.645161,62,1,1
4,colon,24,lasso,0.792045,0.849726,1.317075,0.661035,0.181316,0.466426,0.730682,0.825000,0.636364,0.165033,0.645161,62,1,1
5,colon,24,mi,0.722727,0.796333,1.234316,0.767583,0.221833,0.310317,0.657955,0.725000,0.590909,0.186717,0.645161,62,1,1
9,colon,full,adaptive_hybrid,0.898864,0.943257,1.462049,0.386314,0.119834,0.647727,0.823864,0.875000,0.772727,0.148143,0.645161,62,1,1
13,colon,full,lasso,0.885227,0.912807,1.414851,0.506814,0.124277,0.656355,0.834091,0.850000,0.818182,0.107504,0.645161,62,1,1
11,colon,full,data_only,0.878409,0.926032,1.435349,0.428372,0.123076,0.647727,0.823864,0.875000,0.772727,0.120852,0.645161,62,1,1
15,colon,full,no_fs,0.875568,0.904868,1.402545,0.417400,0.111119,0.725562,0.869318,0.875000,0.863636,0.141341,0.645161,62,1,1
10,colon,full,catboost_rfe,0.869318,0.915049,1.418325,0.481964,0.138141,0.647727,0.823864,0.875000,0.772727,0.131046,0.645161,62,1,1
14,colon,full,mi,0.869318,0.918030,1.422946,0.428896,0.128755,0.642034,0.813636,0.900000,0.727273,0.126070,0.645161,62,1,1
16,colon,full,random,0.862500,0.883407,1.369281,0.441039,0.125783,0.680109,0.836364,0.900000,0.772727,0.127042,0.645161,62,1,3
12,colon,full,hybrid,0.847727,0.882691,1.368171,0.489381,0.138789,0.608882,0.801136,0.875000,0.727273,0.114553,0.645161,62,1,1
17,colon,full,text,0.844318,0.883004,1.368657,0.451499,0.132892,0.616798,0.811364,0.850000,0.772727,0.132095,0.645161,62,1,1
19,golub,24,catboost_rfe,0.998298,0.996862,2.870961,0.074530,0.021336,0.938723,0.969362,0.960000,0.978723,0.015802,0.347222,72,1,1
21,golub,24,hybrid,0.995745,0.992883,2.859502,0.095420,0.028998,0.909357,0.958723,0.960000,0.957447,0.034703,0.347222,72,1,1
18,golub,24,adaptive_hybrid,0.993191,0.989181,2.848842,0.095486,0.027231,0.939388,0.960000,0.920000,1.000000,0.024947,0.347222,72,1,1
20,golub,24,data_only,0.993191,0.988889,2.848000,0.095690,0.028941,0.907651,0.949362,0.920000,0.978723,0.028381,0.347222,72,1,1
22,golub,24,lasso,0.989787,0.985495,2.838224,0.120308,0.032355,0.907651,0.949362,0.920000,0.978723,0.030735,0.347222,72,1,1
24,golub,24,no_fs,0.989787,0.987027,2.842638,0.143257,0.034547,0.938723,0.969362,0.960000,0.978723,0.072483,0.347222,72,1,1
23,golub,24,mi,0.988936,0.984127,2.834286,0.116925,0.033837,0.877447,0.938723,0.920000,0.957447,0.036419,0.347222,72,1,1
26,golub,24,text,0.980426,0.969519,2.792216,0.169433,0.056198,0.783880,0.888085,0.840000,0.936170,0.015687,0.347222,72,1,1
25,golub,24,random,0.959149,0.945074,2.721815,0.273032,0.077518,0.814252,0.898723,0.840000,0.957447,0.093147,0.347222,72,1,3
28,golub,full,catboost_rfe,0.997447,0.995714,2.867657,0.063586,0.019607,0.938723,0.969362,0.960000,0.978723,0.003971,0.347222,72,1,1
30,golub,full,hybrid,0.995745,0.992448,2.858249,0.101560,0.032658,0.909357,0.958723,0.960000,0.957447,0.022647,0.347222,72,1,1
35,golub,full,text,0.994894,0.990760,2.853389,0.116626,0.036234,0.909357,0.958723,0.960000,0.957447,0.012477,0.347222,72,1,1
31,golub,full,lasso,0.993191,0.988206,2.846033,0.128610,0.039963,0.909357,0.958723,0.960000,0.957447,0.006296,0.347222,72,1,1
33,golub,full,no_fs,0.993191,0.990303,2.852073,0.107767,0.028320,0.909357,0.958723,0.960000,0.957447,0.037086,0.347222,72,1,1
32,golub,full,mi,0.992340,0.985880,2.839335,0.117441,0.034161,0.909357,0.958723,0.960000,0.957447,0.018391,0.347222,72,1,1
27,golub,full,adaptive_hybrid,0.991489,0.985099,2.837086,0.149696,0.047812,0.848620,0.928085,0.920000,0.936170,0.015869,0.347222,72,1,1
29,golub,full,data_only,0.988085,0.979641,2.821366,0.165971,0.049182,0.881295,0.948085,0.960000,0.936170,0.041487,0.347222,72,1,1
34,golub,full,random,0.981277,0.981277,2.826077,0.132962,0.029351,0.969536,0.980000,0.960000,1.000000,0.055309,0.347222,72,1,3
39,metabric,64,hybrid,0.661460,0.702573,1.212783,0.669269,0.232857,0.229341,0.614468,0.680870,0.548065,0.068375,0.579307,1904,1,1
36,metabric,64,adaptive_hybrid,0.646955,0.689327,1.189917,0.685900,0.238749,0.232853,0.614958,0.708069,0.521848,0.087051,0.579307,1904,1,1
38,metabric,64,data_only,0.644383,0.694619,1.199052,0.706981,0.246399,0.203702,0.601708,0.669084,0.534332,0.115859,0.579307,1904,1,1
41,metabric,64,mi,0.642925,0.692043,1.194605,0.676239,0.236806,0.210817,0.604473,0.690843,0.518102,0.068543,0.579307,1904,1,1
42,metabric,64,no_fs,0.638504,0.689291,1.189856,0.658709,0.232480,0.205469,0.599450,0.730734,0.468165,0.041923,0.579307,1904,1,1
37,metabric,64,catboost_rfe,0.631070,0.688374,1.188272,0.733199,0.253854,0.199838,0.599375,0.678150,0.520599,0.127991,0.579307,1904,1,1
40,metabric,64,lasso,0.614772,0.667225,1.151765,0.896615,0.281226,0.189265,0.594448,0.664551,0.524345,0.179451,0.579307,1904,1,1
44,metabric,64,text,0.614577,0.672051,1.160095,0.674920,0.239724,0.161114,0.572965,0.785131,0.360799,0.047950,0.579307,1904,1,1
43,metabric,64,random,0.603844,0.654333,1.129511,0.664966,0.236113,0.141016,0.556743,0.851315,0.262172,0.032935,0.579307,1904,1,3
53,metabric,full,text,0.763825,0.808231,1.395170,0.571644,0.194250,0.382320,0.687197,0.785131,0.589263,0.031452,0.579307,1904,1,1
47,metabric,full,data_only,0.759661,0.803793,1.387508,0.576919,0.195971,0.368541,0.681535,0.768812,0.594257,0.030696,0.579307,1904,1,1
48,metabric,full,hybrid,0.758782,0.803112,1.386333,0.576902,0.196258,0.368948,0.681304,0.773345,0.589263,0.026952,0.579307,1904,1,1
45,metabric,full,adaptive_hybrid,0.756984,0.805412,1.390303,0.578108,0.197130,0.360117,0.677566,0.763373,0.591760,0.022475,0.579307,1904,1,1
51,metabric,full,no_fs,0.753109,0.798117,1.377710,0.577950,0.197336,0.360942,0.675449,0.787851,0.563046,0.025162,0.579307,1904,1,1
46,metabric,full,catboost_rfe,0.747523,0.797177,1.376087,0.588797,0.201598,0.348522,0.671495,0.762466,0.580524,0.044262,0.579307,1904,1,1
52,metabric,full,random,0.737052,0.779780,1.346057,0.602964,0.207452,0.348965,0.658774,0.853128,0.464419,0.057742,0.579307,1904,1,3
49,metabric,full,lasso,0.734756,0.782600,1.350924,0.607307,0.207950,0.336974,0.664852,0.767906,0.561798,0.062299,0.579307,1904,1,1
50,metabric,full,mi,0.733975,0.790557,1.364661,0.596658,0.205443,0.338517,0.668337,0.736174,0.600499,0.027342,0.579307,1904,1,1

,created_at,pipeline_version,stage,dataset,sample_regime,repeat,fold,method,condition,k,...,selected_k,selected_alpha,inner_auroc,inner_log_loss,inner_best_auroc,auroc_tolerance,inner_split_seed,n_train,n_selected,train_sample_hash
0,2026-08-13T15:04:17.296228+00:00,4.1.0,core,colon,24,1,1,adaptive_hybrid,real,128.0,...,64,0.50,0.500,2.415922,0.500,0.005,2567994453,24,64,a29a2d0e027adffbb867ff89df581df741103962451871...
1,2026-08-14T04:28:37.589949+00:00,4.1.0,core,colon,24,1,1,catboost_rfe,name_invariant,128.0,...,128,NaN,0.250,2.111087,0.250,0.005,2567994453,24,128,a29a2d0e027adffbb867ff89df581df741103962451871...
2,2026-08-14T04:28:00.464974+00:00,4.1.0,core,colon,24,1,1,data_only,name_invariant,128.0,...,128,NaN,0.500,2.490693,0.500,0.005,2567994453,24,128,a29a2d0e027adffbb867ff89df581df741103962451871...
3,2026-08-14T04:27:59.170326+00:00,4.1.0,core,colon,24,1,1,hybrid,real,128.0,...,64,0.25,0.250,2.098693,0.250,0.005,2567994453,24,64,a29a2d0e027adffbb867ff89df581df741103962451871...
4,2026-08-14T04:28:23.957389+00:00,4.1.0,core,colon,24,1,1,lasso,name_invariant,128.0,...,32,NaN,0.375,2.114524,0.375,0.005,2567994453,24,32,a29a2d0e027adffbb867ff89df581df741103962451871...
5,2026-08-14T04:28:14.872813+00:00,4.1.0,core,colon,24,1,1,mi,name_invariant,128.0,...,64,NaN,0.375,2.356413,0.375,0.005,2567994453,24,64,a29a2d0e027adffbb867ff89df581df741103962451871...
6,2026-08-14T04:28:25.315387+00:00,4.1.0,core,colon,24,1,1,random,name_invariant,128.0,...,32,NaN,0.750,0.970471,0.750,0.005,2567994453,24,32,a29a2d0e027adffbb867ff89df581df741103962451871...
7,2026-08-14T04:28:25.978881+00:00,4.1.0,core,colon,24,1,1,random,name_invariant,128.0,...,32,NaN,0.500,0.870620,0.500,0.005,2567994453,24,32,a29a2d0e027adffbb867ff89df581df741103962451871...
8,2026-08-14T04:28:24.615387+00:00,4.1.0,core,colon,24,1,1,random,name_invariant,128.0,...,32,NaN,0.500,1.699338,0.500,0.005,2567994453,24,32,a29a2d0e027adffbb867ff89df581df741103962451871...
9,2026-08-14T04:27:57.982327+00:00,4.1.0,core,colon,24,1,1,text,real,128.0,...,128,NaN,0.500,1.689230,0.500,0.005,2567994453,24,128,a29a2d0e027adffbb867ff89df581df741103962451871...
10,2026-08-14T04:28:44.371189+00:00,4.1.0,core,colon,24,1,2,adaptive_hybrid,real,128.0,...,32,0.75,0.500,1.968910,0.500,0.005,2940748618,24,32,dade3722c78b6a06171e609d2a3d5ad85768eff5b77d1f...
11,2026-08-14T04:29:24.127131+00:00,4.1.0,core,colon,24,1,2,catboost_rfe,name_invariant,128.0,...,64,NaN,0.250,2.011847,0.250,0.005,2940748618,24,64,dade3722c78b6a06171e609d2a3d5ad85768eff5b77d1f...
12,2026-08-14T04:28:45.066191+00:00,4.1.0,core,colon,24,1,2,data_only,name_invariant,128.0,...,32,NaN,0.125,2.404901,0.125,0.005,2940748618,24,32,dade3722c78b6a06171e609d2a3d5ad85768eff5b77d1f...
13,2026-08-14T04:28:43.127191+00:00,4.1.0,core,colon,24,1,2,hybrid,real,128.0,...,128,0.50,0.375,2.186348,0.375,0.005,2940748618,24,128,dade3722c78b6a06171e609d2a3d5ad85768eff5b77d1f...
14,2026-08-14T04:29:10.427518+00:00,4.1.0,core,colon,24,1,2,lasso,name_invariant,128.0,...,64,NaN,0.125,2.220303,0.125,0.005,2940748618,24,64,dade3722c78b6a06171e609d2a3d5ad85768eff5b77d1f...
15,2026-08-14T04:28:59.556348+00:00,4.1.0,core,colon,24,1,2,mi,name_invariant,128.0,...,32,NaN,0.250,1.906634,0.250,0.005,2940748618,24,32,dade3722c78b6a06171e609d2a3d5ad85768eff5b77d1f...
16,2026-08-14T04:29:12.035977+00:00,4.1.0,core,colon,24,1,2,random,name_invariant,128.0,...,128,NaN,0.750,1.189710,0.750,0.005,2940748618,24,128,dade3722c78b6a06171e609d2a3d5ad85768eff5b77d1f...
17,2026-08-14T04:29:12.757976+00:00,4.1.0,core,colon,24,1,2,random,name_invariant,128.0,...,128,NaN,0.375,2.082277,0.375,0.005,2940748618,24,128,dade3722c78b6a06171e609d2a3d5ad85768eff5b77d1f...
18,2026-08-14T04:29:11.315911+00:00,4.1.0,core,colon,24,1,2,random,name_invariant,128.0,...,64,NaN,0.750,1.178357,0.750,0.005,2940748618,24,64,dade3722c78b6a06171e609d2a3d5ad85768eff5b77d1f...
19,2026-08-14T04:28:41.829077+00:00,4.1.0,core,colon,24,1,2,text,real,128.0,...,32,NaN,0.625,1.296884,0.625,0.005,2940748618,24,32,dade3722c78b6a06171e609d2a3d5ad85768eff5b77d1f...
20,2026-08-14T04:29:30.878505+00:00,4.1.0,core,colon,24,1,3,adaptive_hybrid,real,128.0,...,64,0.75,1.000,0.195521,1.000,0.005,3744995861,24,64,37335c3b67c1dcb9f7c0d624b277cd41013dbdb1bb6c18...
21,2026-08-14T04:30:10.189641+00:00,4.1.0,core,colon,24,1,3,catboost_rfe,name_invariant,128.0,...,64,NaN,1.000,0.158619,1.000,0.005,3744995861,24,64,37335c3b67c1dcb9f7c0d624b277cd41013dbdb1bb6c18...
22,2026-08-14T04:29:31.648507+00:00,4.1.0,core,colon,24,1,3,data_only,name_invariant,128.0,...,32,NaN,1.000,0.254107,1.000,0.005,3744995861,24,32,37335c3b67c1dcb9f7c0d624b277cd41013dbdb1bb6c18...
23,2026-08-14T04:29:29.584895+00:00,4.1.0,core,colon,24,1,3,hybrid,real,128.0,...,128,0.25,1.000,0.120741,1.000,0.005,3744995861,24,128,37335c3b67c1dcb9f7c0d624b277cd41013dbdb1bb6c18...
24,2026-08-14T04:29:56.454434+00:00,4.1.0,core,colon,24,1,3,lasso,name_invariant,128.0,...,32,NaN,1.000,0.099974,1.000,0.005,3744995861,24,32,37335c3b67c1dcb9f7c0d624b277cd41013dbdb1bb6c18...
25,2026-08-14T04:29:46.124431+00:00,4.1.0,core,colon,24,1,3,mi,name_invariant,128.0,...,32,NaN,1.000,0.190063,1.000,0.005,3744995861,24,32,37335c3b67c1dcb9f7c0d624b277cd41013dbdb1bb6c18...
26,2026-08-14T04:29:57.949253+00:00,4.1.0,core,colon,24,1,3,random,name_invariant,128.0,...,64,NaN,1.000,0.145396,1.000,0.005,3744995861,24,64,37335c3b67c1dcb9f7c0d624b277cd41013dbdb1bb6c18...
27,2026-08-14T04:29:58.646254+00:00,4.1.0,core,colon,24,1,3,random,name_invariant,128.0,...,128,NaN,1.000,0.223524,1.000,0.005,3744995861,24,128,37335c3b67c1dcb9f7c0d624b277cd41013dbdb1bb6c18...
28,2026-08-14T04:29:57.176252+00:00,4.1.0,core,colon,24,1,3,random,name_invariant,128.0,...,128,NaN,1.000,0.597659,1.000,0.005,3744995861,24,128,37335c3b67c1dcb9f7c0d624b277cd41013dbdb1bb6c18...
29,2026-08-14T04:29:28.197054+00:00,4.1.0,core,colon,24,1,3,text,real,128.0,...,128,NaN,1.000,0.217683,1.000,0.005,3744995861,24,128,37335c3b67c1dcb9f7c0d624b277cd41013dbdb1bb6c18...

,dataset,sample_regime,n_outer_repeats,metric,reference_method,comparator_method,reference_auroc,comparator_auroc,delta_auroc,ci_level,ci_lower,ci_upper,p_two_sided,bootstrap_iterations,n_samples,p_holm,significant_0_05_holm
4,colon,24,1,auroc,adaptive_hybrid,mi,0.852273,0.722727,1.295455e-01,0.95,0.052349,2.194363e-01,0.001200,5000,62,0.053989,False
3,colon,24,1,auroc,adaptive_hybrid,lasso,0.852273,0.792045,6.022727e-02,0.95,-0.017870,1.456593e-01,0.132773,5000,62,1.000000,False
1,colon,24,1,auroc,adaptive_hybrid,data_only,0.852273,0.793182,5.909091e-02,0.95,-0.009524,1.425618e-01,0.109578,5000,62,1.000000,False
2,colon,24,1,auroc,adaptive_hybrid,hybrid,0.852273,0.794318,5.795455e-02,0.95,-0.016719,1.463436e-01,0.141972,5000,62,1.000000,False
7,colon,24,1,auroc,adaptive_hybrid,text,0.852273,0.813636,3.863636e-02,0.95,-0.036009,1.211760e-01,0.317536,5000,62,1.000000,False
5,colon,24,1,auroc,adaptive_hybrid,no_fs,0.852273,0.829545,2.272727e-02,0.95,-0.030953,7.880792e-02,0.406319,5000,62,1.000000,False
6,colon,24,1,auroc,adaptive_hybrid,random,0.852273,0.829545,2.272727e-02,0.95,-0.034095,8.409938e-02,0.413117,5000,62,1.000000,False
0,colon,24,1,auroc,adaptive_hybrid,catboost_rfe,0.852273,0.837500,1.477273e-02,0.95,-0.025000,5.934633e-02,0.466307,5000,62,1.000000,False
15,colon,full,1,auroc,adaptive_hybrid,text,0.898864,0.844318,5.454545e-02,0.95,0.003174,1.150332e-01,0.036793,5000,62,1.000000,False
10,colon,full,1,auroc,adaptive_hybrid,hybrid,0.898864,0.847727,5.113636e-02,0.95,0.010811,1.025641e-01,0.009198,5000,62,0.386323,False
14,colon,full,1,auroc,adaptive_hybrid,random,0.898864,0.862500,3.636364e-02,0.95,-0.004900,8.864865e-02,0.098780,5000,62,1.000000,False
8,colon,full,1,auroc,adaptive_hybrid,catboost_rfe,0.898864,0.869318,2.954545e-02,0.95,-0.007679,7.142857e-02,0.125575,5000,62,1.000000,False
12,colon,full,1,auroc,adaptive_hybrid,mi,0.898864,0.869318,2.954545e-02,0.95,-0.005232,7.613772e-02,0.115977,5000,62,1.000000,False
13,colon,full,1,auroc,adaptive_hybrid,no_fs,0.898864,0.875568,2.329545e-02,0.95,-0.017425,7.380952e-02,0.309138,5000,62,1.000000,False
9,colon,full,1,auroc,adaptive_hybrid,data_only,0.898864,0.878409,2.045455e-02,0.95,-0.009293,5.751662e-02,0.180364,5000,62,1.000000,False
11,colon,full,1,auroc,adaptive_hybrid,lasso,0.898864,0.885227,1.363636e-02,0.95,-0.039019,6.469498e-02,0.584683,5000,62,1.000000,False
22,golub,24,1,auroc,adaptive_hybrid,random,0.993191,0.959149,3.404255e-02,0.95,0.002314,8.124161e-02,0.029594,5000,72,1.000000,False
23,golub,24,1,auroc,adaptive_hybrid,text,0.993191,0.980426,1.276596e-02,0.95,0.000000,3.376592e-02,0.059588,5000,72,1.000000,False
20,golub,24,1,auroc,adaptive_hybrid,mi,0.993191,0.988936,4.255319e-03,0.95,-0.001702,1.666667e-02,0.469506,5000,72,1.000000,False
19,golub,24,1,auroc,adaptive_hybrid,lasso,0.993191,0.989787,3.404255e-03,0.95,-0.002508,1.508429e-02,0.589082,5000,72,1.000000,False
21,golub,24,1,auroc,adaptive_hybrid,no_fs,0.993191,0.989787,3.404255e-03,0.95,-0.006689,1.924619e-02,0.825835,5000,72,1.000000,False
17,golub,24,1,auroc,adaptive_hybrid,data_only,0.993191,0.993191,1.110223e-16,0.95,-0.006349,5.323869e-03,1.000000,5000,72,1.000000,False
18,golub,24,1,auroc,adaptive_hybrid,hybrid,0.993191,0.995745,-2.553191e-03,0.95,-0.012153,3.734827e-03,0.644271,5000,72,1.000000,False
16,golub,24,1,auroc,adaptive_hybrid,catboost_rfe,0.993191,0.998298,-5.106383e-03,0.95,-0.019097,0.000000e+00,0.398720,5000,72,1.000000,False
30,golub,full,1,auroc,adaptive_hybrid,random,0.991489,0.981277,1.021277e-02,0.95,-0.013310,4.818965e-02,0.774245,5000,72,1.000000,False
25,golub,full,1,auroc,adaptive_hybrid,data_only,0.991489,0.988085,3.404255e-03,0.95,-0.003148,1.203160e-02,0.415517,5000,72,1.000000,False
28,golub,full,1,auroc,adaptive_hybrid,mi,0.991489,0.992340,-8.510638e-04,0.95,-0.007305,5.454545e-03,0.851430,5000,72,1.000000,False
27,golub,full,1,auroc,adaptive_hybrid,lasso,0.991489,0.993191,-1.702128e-03,0.95,-0.007273,1.110223e-16,0.612278,5000,72,1.000000,False
29,golub,full,1,auroc,adaptive_hybrid,no_fs,0.991489,0.993191,-1.702128e-03,0.95,-0.015542,1.116071e-02,0.795841,5000,72,1.000000,False
31,golub,full,1,auroc,adaptive_hybrid,text,0.991489,0.994894,-3.404255e-03,0.95,-0.014815,4.255888e-03,0.497900,5000,72,1.000000,False
26,golub,full,1,auroc,adaptive_hybrid,hybrid,0.991489,0.995745,-4.255319e-03,0.95,-0.013022,0.000000e+00,0.214757,5000,72,1.000000,False
24,golub,full,1,auroc,adaptive_hybrid,catboost_rfe,0.991489,0.997447,-5.957447e-03,0.95,-0.019231,8.510638e-04,0.203959,5000,72,1.000000,False
38,metabric,64,1,auroc,adaptive_hybrid,random,0.646955,0.603844,4.311078e-02,0.95,0.021128,6.540945e-02,0.000400,5000,1904,0.019196,True
39,metabric,64,1,auroc,adaptive_hybrid,text,0.646955,0.614577,3.237737e-02,0.95,0.007324,5.711348e-02,0.011598,5000,1904,0.475505,False
35,metabric,64,1,auroc,adaptive_hybrid,lasso,0.646955,0.614772,3.218325e-02,0.95,0.011474,5.301988e-02,0.001200,5000,1904,0.053989,False
32,metabric,64,1,auroc,adaptive_hybrid,catboost_rfe,0.646955,0.631070,1.588506e-02,0.95,0.000422,3.090914e-02,0.043991,5000,1904,1.000000,False
37,metabric,64,1,auroc,adaptive_hybrid,no_fs,0.646955,0.638504,8.451018e-03,0.95,-0.003072,2.013416e-02,0.148370,5000,1904,1.000000,False
36,metabric,64,1,auroc,adaptive_hybrid,mi,0.646955,0.642925,4.029415e-03,0.95,-0.009877,1.795016e-02,0.557888,5000,1904,1.000000,False
33,metabric,64,1,auroc,adaptive_hybrid,data_only,0.646955,0.644383,2.571582e-03,0.95,-0.010218,1.564694e-02,0.661468,5000,1904,1.000000,False
34,metabric,64,1,auroc,adaptive_hybrid,hybrid,0.646955,0.661460,-1.450476e-02,0.95,-0.028016,-7.855625e-04,0.039992,5000,1904,1.000000,False
44,metabric,full,1,auroc,adaptive_hybrid,mi,0.756984,0.733975,2.300898e-02,0.95,0.011333,3.418709e-02,0.000400,5000,1904,0.019196,True
43,metabric,full,1,auroc,adaptive_hybrid,lasso,0.756984,0.734756,2.222799e-02,0.95,0.009302,3.517961e-02,0.000400,5000,1904,0.019196,True
46,metabric,full,1,auroc,adaptive_hybrid,random,0.756984,0.737052,1.993259e-02,0.95,0.006974,3.317105e-02,0.001600,5000,1904,0.068786,False
40,metabric,full,1,auroc,adaptive_hybrid,catboost_rfe,0.756984,0.747523,9.461202e-03,0.95,0.000156,1.900223e-02,0.047590,5000,1904,1.000000,False
45,metabric,full,1,auroc,adaptive_hybrid,no_fs,0.756984,0.753109,3.875482e-03,0.95,-0.007344,1.541268e-02,0.517896,5000,1904,1.000000,False
42,metabric,full,1,auroc,adaptive_hybrid,hybrid,0.756984,0.758782,-1.797391e-03,0.95,-0.007350,4.031311e-03,0.550290,5000,1904,1.000000,False
41,metabric,full,1,auroc,adaptive_hybrid,data_only,0.756984,0.759661,-2.676844e-03,0.95,-0.008033,2.656384e-03,0.327934,5000,1904,1.000000,False
47,metabric,full,1,auroc,adaptive_hybrid,text,0.756984,0.763825,-6.840384e-03,0.95,-0.014229,4.996274e-04,0.068786,5000,1904,1.000000,False

## 6. 표·시각화 생성 및 완료 검사

공식 성능, calibration, 선택 안정성, inner holdout이 선택한 k·alpha, paired-bootstrap CI와
자원 사용량을 PNG·SVG·PDF·CSV로 저장합니다.

In [10]:
RUN_FIGURES = True
if RUN_FIGURES:
    figure_report = exp.generate_standard_figures(CFG)
    display(figure_report)
    if figure_report['errors']:
        print('Figure warnings:', figure_report['errors'])
    completion = exp.experiment_completion_report(CFG)
    display(completion)
    assert completion.loc[completion['stage'] == 'TOTAL', 'complete'].iloc[0]

C:\Users\user\Desktop\2026 캡스톤_2차\2차 실험_KDMS\3차\EXPERIMENT_CODE\llmfs_pipeline.py:2507: RuntimeWarning: Mean of empty slice
  "mean_kuncheva": float(np.nanmean(kuncheva)) if kuncheva else float("nan"),

{'prediction_rows': 44862,
 'repeat_metric_rows': 68,
 'fold_metric_rows': 332,
 'fold_variability_rows': 68,
 'summary_rows': 68,
 'stability_rows': 68,
 'selection_frequency_rows': 22067,
 'primary_oof_metric_rows': 54,
 'paired_bootstrap_rows': 48,
 'compatibility_rows': 0,
 'semantic_rows': 0,
 'nested_tuning_decision_rows': 300,
 'completion': [{'stage': 'smoke',
   'expected': 2,
   'completed': 2,
   'remaining': 0,
   'complete': True},
  {'stage': 'core',
   'expected': 330,
   'completed': 330,
   'remaining': 0,
   'complete': True},
  {'stage': 'TOTAL',
   'expected': 332,
   'completed': 332,
   'remaining': 0,
   'complete': True}],
 'figures': ['C:\\Users\\user\\Desktop\\2026 캡스톤_2차\\2차 실험_KDMS\\3차\\RESULTS_LIGHT_1X5_HOLDOUT\\figures\\core_auroc_vs_sample_size.png',
  'C:\\Users\\user\\Desktop\\2026 캡스톤_2차\\2차 실험_KDMS\\3차\\RESULTS_LIGHT_1X5_HOLDOUT\\figures\\core_auroc_performance_heatmap.png',
  'C:\\Users\\user\\Desktop\\2026 캡스톤_2차\\2차 실험_KDMS\\3차\\RESULTS_LIGHT_1X5_HOLDOUT\\figures\\selection_stability_mean_kuncheva.png',
  'C:\\Users\\user\\Desktop\\2026 캡스톤_2차\\2차 실험_KDMS\\3차\\RESULTS_LIGHT_1X5_HOLDOUT\\figures\\selection_stability_mean_jaccard.png',
  'C:\\Users\\user\\Desktop\\2026 캡스톤_2차\\2차 실험_KDMS\\3차\\RESULTS_LIGHT_1X5_HOLDOUT\\figures\\core_resource_usage.png',
  'C:\\Users\\user\\Desktop\\2026 캡스톤_2차\\2차 실험_KDMS\\3차\\RESULTS_LIGHT_1X5_HOLDOUT\\figures\\nested_tuning_choices.png',
  'C:\\Users\\user\\Desktop\\2026 캡스톤_2차\\2차 실험_KDMS\\3차\\RESULTS_LIGHT_1X5_HOLDOUT\\figures\\paired_bootstrap_auroc.png',
  'C:\\Users\\user\\Desktop\\2026 캡스톤_2차\\2차 실험_KDMS\\3차\\RESULTS_LIGHT_1X5_HOLDOUT\\figures\\core_golub_calibration.png',
  'C:\\Users\\user\\Desktop\\2026 캡스톤_2차\\2차 실험_KDMS\\3차\\RESULTS_LIGHT_1X5_HOLDOUT\\figures\\core_colon_calibration.png',
  'C:\\Users\\user\\Desktop\\2026 캡스톤_2차\\2차 실험_KDMS\\3차\\RESULTS_LIGHT_1X5_HOLDOUT\\figures\\core_metabric_calibration.png'],
 'errors': []}

   stage  expected  completed  remaining  complete
0  smoke         2          2          0      True
1   core       330        330          0      True
2  TOTAL       332        332          0      True

## 7. 최종 출력 위치

- 공식 성능: `RESULTS_LIGHT_1X5_HOLDOUT/metrics/primary_core_oof_metrics.csv`
- inner 선택 결과: `nested_tuning_decisions.csv`
- paired bootstrap: `paired_bootstrap_auroc.csv`
- 안정성: `selection_stability.csv`, `selection_frequency.csv`
- 그림: `RESULTS_LIGHT_1X5_HOLDOUT/figures`
- 오류와 실행 로그: `RESULTS_LIGHT_1X5_HOLDOUT/logs`

In [11]:
print('Experiment output root:', CFG['results_root'])
print('Primary metrics:', PATHS['metrics'] / 'primary_core_oof_metrics.csv')
print('Nested decisions:', PATHS['metrics'] / 'nested_tuning_decisions.csv')
print('Paired bootstrap:', PATHS['metrics'] / 'paired_bootstrap_auroc.csv')
print('Figures:', PATHS['figures'])

Experiment output root: C:\Users\user\Desktop\2026 캡스톤_2차\2차 실험_KDMS\3차\RESULTS_LIGHT_1X5_HOLDOUT
Primary metrics: C:\Users\user\Desktop\2026 캡스톤_2차\2차 실험_KDMS\3차\RESULTS_LIGHT_1X5_HOLDOUT\metrics\primary_core_oof_metrics.csv
Nested decisions: C:\Users\user\Desktop\2026 캡스톤_2차\2차 실험_KDMS\3차\RESULTS_LIGHT_1X5_HOLDOUT\metrics\nested_tuning_decisions.csv
Paired bootstrap: C:\Users\user\Desktop\2026 캡스톤_2차\2차 실험_KDMS\3차\RESULTS_LIGHT_1X5_HOLDOUT\metrics\paired_bootstrap_auroc.csv
Figures: C:\Users\user\Desktop\2026 캡스톤_2차\2차 실험_KDMS\3차\RESULTS_LIGHT_1X5_HOLDOUT\figures